### ISSUE TITLE
clean up the command structure for dbt test

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#109]
few concerns:

- the more common thing to do will actually be to run `dbt test --validate` rather than `dbt test`. it's strange that the more common use case is the one where you need to supply a flag.
- "test" vs "validate" as verbs don't have super-clear meanings. we should think for a bit here about what we want these terms to be prior to really launching testing and building docs around this stuff.
- when i use `dbt test --validate` i would really prefer that it not do the part where it builds the "limit 0" temporary tables. i would imagine running this validation once a day or even multiple times a day, on already-working dbt models. there is no need to build these test models in this environment because we're actually validating the real dbt models.

**Comment by drewbanin** [comment]
i rolled this out as a part of 0.4.1

```
# run models
dbt run
# create "limit 0" views and delete them afterwards. model names are prefixed with "test_"
dbt run --dry
# run schema validations from schema.yml files
dbt test 
```
