### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by b-ryan** [analyst-collective/dbt#11]
Thoughts on the project structure:

I would make `dbt/task/*.py` just be one file: `dbt/tasks.py`. Generally you shouldn't make Python packages unless things start to get big. And the one-class-per-file is not really ever the way to split it up.

--------------

`main.py`:

You could have each task set up its subparser. I think your structure here came from `mario` so this one is my bad. But I wish I had done:

```python
# tasks.py

class Clean:
    @classmethod
    def setup_subparser(cls, subs):
        sub = subs.add_parser('clean')
        return sub

tasks = [
    Clean,
    # ...
]

# main.py
import tasks

# ...

    p = argparse.ArgumentParser(prog='dbt: data build tool')
    subs = p.add_subparsers()

    for task in tasks.tasks:
        sub = task.setup_subparser(subs)
        sub.set_defaults(cls=cls)
```

**Comment by drewbanin** [comment]
@b-ryan thanks for the feedback! This will probably be refactored soon and I'll definitely borrow from your ideas here. Thanks!
