### ISSUE TITLE
{{run_start_at}}

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#115]
tristan [9:33 PM]  
dude you know what we need another set of parameters

[9:33]  
in the environment

[9:33]  
timestamps--especially, {{run_start_at}}

[9:33]  
i'm just thinking about in a streaming enviroment where you have a big build, you don't want later tables to pick up shit that earlier tables didn't get to see...

[9:34]  
so you'd always do `where created_at < {{run_start_at}}`

[9:35]  
although that wouldn't work in all cases. they'd still see updated records. hmm. ok well thoughts for another day.

drew [9:35 PM]  
it would probably be `where fivetran_synced_at < {{run_start_at}}`

tristan [9:35 PM]  
oh. hm yeah i could see that.

**Comment by drewbanin** [comment]
0.5.1 release
