### ISSUE TITLE
in-model configs don't respect enabled

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#122]
i added this to the beginning of a model and the compiler didn't respect it:

{{ config(

  enabled = "false"

) }}

caused build errors. for now i put this config back into `dbt_project.yml`.

**Comment by drewbanin** [comment]
@jthandy you should use the constant `false`, not the string `"false"` :)

in model enabled configs definitely do work! Just tested with 0.4.2. Closing this -- reopen if you think this is a different issue

**Comment by jthandy** [comment]
I think there is something specifically going on with this config. It's still failing at the compile stage.
