### ISSUE TITLE
allow dbt to run queries interactively

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#132]
The further dbt gets away from raw SQL, the more annoying it gets to run dbt queries interactively as you're working on them. Right now, the process is as follows to write a new model:
- write and test a SQL query
- convert it into dbt syntax (not that hard right now but will get more involved)
- deploy it as a model

The workflow to edit an existing model is more annoying: 
- run compile
- navigate to the target folder, find the model compiled code, copy/paste it into query editor and make changes to stripe out just the select syntax.
- run, make changes, test
- re-convert the query back into dbt syntax
- redeploy as model.

In the future, these processes will become more and more of a headache. (Imagine a world with more macros, import statements, etc!) The dbt model code will only diverge further from the raw SQL.

One way of addressing this is to allow dbt to run queries interactively from the CLI. This would work as follows: 
- `dbt query modelname` would take the SQL SELECT from the body of a given model, compile it (without the DDL), and run it using the appropriate database driver, then output the results to the command line.

This would allow users to save the step of converting back and forth from raw SQL. It could also become a VIM binding that you could run as you're developing a model; it could be possible to skip the raw SQL step altogether.

**Comment by jthandy** [comment]
I think this is a bad feature idea. Because it was originally mine, I'm killing it.

**Comment by NordinLars** [comment]
Was there ever a solution to “The further dbt gets away from raw SQL, the more annoying it gets to run dbt queries interactively as you're working on them”?
@jthandy

**Comment by jthandy** [comment]
Hah! Wow--I hadn't thought about this issue in *forever*! Can't believe you found this ;)

This is still something that we think a lot about, and we have invested in doing some experimentation around it. We don't have anything to share at this point but you should expect there to be improvements to this workflow in 2019. It definitely won't take the form of the suggestion in the initial issue, but my 2016 self was on target in describing the problem :)

**Comment by moltar** [comment]
Would love to home something like this:

1. Edit in IDE and save
2. dbt watches for changes triggers rebuild and refresh of the data automatically

That feedback loop would be super tight!

The big issue I see is dependencies, of course. It'd have to refresh the graph somehow.
