### ISSUE TITLE
tables only dbt run

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#137]
In production, we want runs to be as non-destructive as possible. If a given project has 4 incremental models and 50 views and no "table" models, that means all dbt production runs can avoid tearing down any database objects. There are two changes we need to make to actually get that to happen:
1. We need to avoid rebuilding dependent views if `dbt run` specifies only incremental models. Currently, these views get rebuilt even though there is no need for this.
2. We need to have a graph selection mechanism for model materialization so that we can select only incremental models (or only tables, etc.) from the graph.

This combination will result in a significantly cleaner production run; tearing down objects in production should be done only as needed.

**Comment by drewbanin** [comment]
leave views alone, truncate + re-insert into tables, run incremental models.

This is for production use-cases where we don't want to trash everything and rebuild from scratch

**Comment by drewbanin** [comment]
see also: https://github.com/analyst-collective/dbt/issues/140

**Comment by drewbanin** [comment]
```bash
dbt run --non-destructive
```
