### ISSUE TITLE
deprecate dry run

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#142]
There are certain errors that only occur when data is actually selected from the underlying table. One example is a divide-by-zero error.

When a model is materialized as a table, it must perform the select, which will cause it to fail if it experiences a divide-by-zero error. When that same model is materialized as a view (as it would be in `dbt run --dry`, this error will not occur. This has the potential to give users a false sense of security about the success or failure of their usage of `dbt run` after they have completed a successful `dbt run --dry`.

There is a good solution to this: `dbt run --dry` should, instead of materializing everything as a view, materialize all tables or incrementals as tables, with two changes applied:
- limit x, where x is defined in config somewhere (project level? model level?)
- order by random()

This will allow the dry run to actually materialize a subset of the total rows in the table and provide significantly increased confidence that a subsequent run will succeed. It will still be possible with this strategy for the dry run to succeed but the run to fail in the case that the random subset doesn't contain the problematic records, but there is an inherent tradeoff between speed and disk space of the dry run and the its relative accuracy. This strategy allows the user to make that tradeoff by controlling the number of rows validated.

**Comment by drewbanin** [comment]
This is a good idea

**Comment by jthandy** [comment]
I kind of think that `dbt run --dry` is a feature that just hasn't really found a usage. Because dbt allows for test and production environments, really, testing is done in a test environment via a full `dbt run`. I would never suggest that someone make a realistic assessment of whether or not a set of models would run or not based on the results of `dbt run --dry`, and because of that I feel bad continuing to support the feature. I actually don't think it makes sense to do *any* amount of work to attempt to improve it from its current state, because I think the best way to actually test whether or not a run will be successful is to actually do the run! 

If there are improvements to be made here, I think they are more focused on seeding separate test environments that prevent resource contention on production resources, but that's a completely separate feature.

Would you be supportive of deprecating `dbt run --dry` @drewbanin? Have you literally ever used it, ever? I have not.

**Comment by drewbanin** [comment]
@jthandy I think there's some merit to "dry running" but i think the current approach is a bad one.

It would be super useful to have dbt go through all the steps of executing a model without actually running any DDL statements. Consider that we feel pretty comfortable with dbt, but new users might be a little intimidated by the opaqueness of `dbt run<enter>`. 

I think a great implementation of `dbt run --dry` would show output very similar to `dbt run` (with the correct schema, table names, materializations, threads, etc) without executing any SQL.

The current implementation of `dbt run --dry` could more appropriately be called `dbt run --damp` b/c it actually hits the db...

**Comment by jthandy** [comment]
I get what you're saying, but you're essentially just describing a feature that we don't currently have. The feature that we currently do have is, I believe, one that is actually detrimental to have because it could potentially give a sense of false confidence to a user. And building the feature that you describe, while certainly interesting, wouldn't be high on my list of candidates to build in the very near future. As such—what do you propose should be done with `dbt run --dry` in the meantime? Let it continue to exist as-is?

**Comment by drewbanin** [comment]
Yeah, two options here:
1) leave it alone until we can do it better/differently
2) remove it until we can do it better/differently

I vote the latter, especially given that the current, bad, implementation adds heaps of undue complexity to the runner code

**Comment by jthandy** [comment]
I totally agree. Let's validate with some additional data when you add better instrumentation and then we'll make a call.

**Comment by cmcarthur** [comment]
We decided to deprecate dry run

**Comment by drewbanin** [comment]
removed in [0.7.0](https://github.com/analyst-collective/dbt/blob/development/CHANGELOG.md#deprecations)

**Comment by dbrtly** [comment]
Even if the user ran a query with 
"select column_a/column_b", executing the run will only throw an error is you have a record with condition z: (where column_b = 0).

The user would have a misleading indicator of a successful run and risk errors in runs on future data when condition z is true.  

A macro for safe_divide and static analysis (pre-commit test?) that recommends using the macro whenever the character '/' occurs in the select body and it's not parsed as a string might achieve better outcomes.
