### ISSUE TITLE
rationalize naming between target and run-target

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#144]
the CLI refers to them as "target"s. `profiles.yml` refers to them as "run-target"s. either we should change the config parameter to just "target" or we should call it "default-target".

**Comment by drewbanin** [comment]
@jthandy i remember talking about this a while back. This would be a breaking change. That ok? I figure it's better to do it now than later

**Comment by jthandy** [comment]
I think it's a confusing naming convention as-is. I agree that it would be breaking; maybe we could introduce a deprecation pathway? Deprecate it by 0.6.0? And in the meantime spit out warnings when we detected it in a run?
