### ISSUE TITLE
add target variable to templating environment

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#149]
this would allow the user to do things like this in their models:

```
select *
from snowplow.sessions
{ if target == dev }
where session_start_timestamp between 1 and 7 days ago
{ end }
```

there is a ton of value to be had out of an extremely simple environment variable, this is just one example.

make sure to add this usage to the best practices guide in the help docs once this feature is added.

**Comment by drewbanin** [comment]
This is a good idea and it should be super quick to add. I think that in practice, relying on the name of the `target` is a bad idea. Different people within the same org can have different target names b/c it's defined in the `profiles.yml` file. Moreover, there's no way this would work reliably in a package management world.

If the divide is dev/prod, should we add an `environment` var to the target? That sounds like a more dependable way to accomplish what you're looking for

**Comment by jthandy** [comment]
We talked about this yesterday. I'm still not sure I agree with you. Rails has `database.yml` and the three entries in there (development, test, production) are standard across rails deployments. What is the thing that is preventing us from doing the same? If `target` isn't that, then I think we should change it to that. People don't need arbitrary control over this, I think we should be opinionated about what the correct usage is here. I would be ok going so far as to validate acceptable values. You can name your profile whatever you want, but your target should be dev/prod/test. If that's not what you're thinking target is, then let's talk further.
