### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#15]
I am a bit worried about our namespaces. It seems like we have three things: models, tests, analyses, and they all have their own namespace tree. Seems weird. I wonder if top level shouldn't be `pardot` and then within that there are `tests`, `models`, `analysis`. There could potentially be other elements as well.

Curious to know whether this has occurred to you / if you see it as a problem. Might be a useful cleanup.

**Comment by drewbanin** [comment]
@jthandy i like this idea! I don't think we should mandate a folder structure, but i do think there should be an opinionated way of doing things. I think that opinion should be something like you mentioned:
```
model_name/
  - tests/
  - models/
  - analysis/
```

Need to give this some more thought...

**Comment by jthandy** [comment]
Right now, all of the stuff within the old analytics repo has been split into its own repositories. This creates a bunch of really simple repos with narrow focus, which solves much of this problem. 

I do think that this is going to have its own challenges once we begin to build out more extensive analytical repos--I could imagine rjmetrics/analytics as a repo for all of our internal analytics, and at that point I would think you'd want modules that contain their own folder structures.

Regardless, at this point I don't feel the pain around this because of package management. I'm going to close this for now and we can reevaluate later as needed.
