### ISSUE TITLE
top-level config scope

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#161]
tristan [1:01]  
is it possible to create a configuration at the level of `models:`

[1:01]  
so that it would be across all models, not just within a specific package?

[1:01]  
that's the ideal place to put the pre-hook and post-hook for audit tables.

drew [1:03 PM]  
yeah, i was thinking about that too! Not currently possible, but it’s  a good idea and shouldn’t be super tricky to implement

[1:03]  
kind of like our `model-defaults` from earlier

tristan [1:03 PM]  
yes, but not some separate dumb thing.

**Comment by drewbanin** [comment]
0.5.1 release
