### ISSUE TITLE
User-friendly error messages for dbt commands

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#19]
If there is missing but required config when attempting to run dbt commands, should give user friendly outputs.
<img width="945" alt="screen shot 2016-04-06 at 2 44 33 pm" src="https://cloud.githubusercontent.com/assets/2341841/14328776/308c4514-fc06-11e5-8b40-37adeec80273.png">

**Comment by drewbanin** [comment]
also: throw error if you `dbt run` and the `target-path` dir doesn't exist

**Comment by drewbanin** [comment]
https://github.com/analyst-collective/dbt/pull/27
