### ISSUE TITLE
Switch run-targets via command line

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#20]
There is an ability in config to define multiple run-targets. It seems like I should be able to specify a run target as an option in the command line, because otherwise the facility to switch between them is fairly awkward.

In general, the ability to define / switch between run targets should be thought through and documented. It will be common to use dbt in multiple environments at once from within a single machine (I'm trying to do this now and struggling) and we need to support it.

**Comment by drewbanin** [comment]
:+1:

**Comment by drewbanin** [comment]
Instead of switching targets, this is accomplished by switching profiles. Pretty much the same thing (for now)

https://github.com/analyst-collective/dbt/pull/23
