### ISSUE TITLE
implement hooks

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#22]
We need to create "hooks" for the core dbt tasks. Hooks would simply offer the opportunity to write sql-based scripts that would execute before and after the various stages in the dbt commands.

One example use for a hook would be setting grants for a schema and all tables in it to certain users after that schema is created. There's no need for dbt to set those grants itself, this is a generic way to allow users to do this or many other tasks associated with dbt processes.

For now, I could imagine pre and post hooks for dbt run. Since the other commands don't actually interface with the database, I'm not sure that the concept makes as much sense there. If anyone can imagine a use, I'd be open to it though.

In the future it might make sense to implement hooks for individual models, but I don't see the need to do that today.

**Comment by drewbanin** [comment]
This is a good idea

**Comment by drewbanin** [comment]
@jthandy is this still something you think we should queue up?

**Comment by jthandy** [comment]
I'd rather make progress on testing for the moment than implement this. This is cool but I don't think it's extremely pressing...

**Comment by jthandy** [comment]
I don't feel nearly as much need for this as I once did. The core dbt workflow is clean and getting cleaner. There doesn't seem to be some gaping hole at the moment that could be filled by hooks. We can take this up again in the future if there's a clear need for it.

**Comment by jthandy** [comment]
Ok I take this back. there is a big problem that I need to use this to fix: `grant` statements! Right now I'm using dbt on one project as a non-admin user, and I need to manually run grant statements on tables every time I do `dbt run`. Ideally, I would be able to configure a post-hook to accomplish this:

{{config(post-hook="grant select on "+self())}}

**Comment by manishkukreja88** [comment]
Can I run multiple SQL statements in an SQL post hook? In addition to granting full access of the table, I also want to log an entry to an audit table in Redshift for logging process start and end times.

**Comment by jtcohen6** [comment]
Yes, hooks can accept a list of SQL statements ([docs](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook/))
