### ISSUE TITLE
issue while running incremental model

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#227]
I'm getting the following error when running my models. I believe what has happened is that a column is getting added and the old column is getting dropped, but there are views that depend on that column and it's not doing a cascade. I'm surprised that it's not cascading...?

```
20 of 50 ERROR creating incremental model dbt_jthandy.snowplow_enriched_events . [ERROR in 113.01s]
Error executing target/build/Snowplow/events/snowplow_enriched_events.sql
cannot drop table dbt_jthandy.snowplow_enriched_events column refr_urlpath because other objects depend on it
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

Or maybe I'm understanding the error incorrectly...

**Comment by jthandy** [comment]
@drewbanin take a look, i know that incremental models aren't perfect when schema changes exist, but i think the only thing going on here is a varchar widening, which i thought we handled pretty well.

**Comment by drewbanin** [comment]
indeed, it looks like we don't `drop ... cascade`.
Code is here: https://github.com/analyst-collective/dbt/blob/development/dbt/schema.py#L278
