### ISSUE TITLE
setting models to disabled at root level doesn't work

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#228]
If I want to disable all models at the root level so that I can go in and select individual models to enable, this doesn't work--for some reason that root level doesn't seem to respect `enabled = false`.

**Comment by drewbanin** [comment]
@jthandy what version/branch of dbt is this happening on?

- write an integration test for this (presumably failing)
- fix it

I'm curious if this affects other root-level configs. My guess is that enabled isn't isolated.

**Comment by jthandy** [comment]
```
installed version: 0.5.4
   latest version: 0.5.4
Up to date!
```

I know that pre-hooks and post-hooks work at a global level. Haven't tested everything else.

**Comment by drewbanin** [comment]
fixed this in the minor-improvements milestone
