### ISSUE TITLE
Consider implementing run locking

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#248]
Could be a useful feature, although we haven't heard the need for it directly from users yet. Check out how Snowplow implemented here:

https://github.com/snowplow/sql-runner/pull/75

**Comment by drewbanin** [comment]
yeah -- this is interesting. We'd probably want to lock at the schema level. That way multiple users can run dbt in their own schemas, but the `analytics` schema (for instance) can only have one writer at a time. let me think a little more about that

**Comment by cmcarthur** [comment]
this relies on [consul](https://www.consul.io/) which is not really easily included into an analytics stack. the most interesting approach for this IMO is to use SQL to implement run-locking. on that topic, it'd be interesting to talk about keeping a record of dbt runs in the warehouse.
