### ISSUE TITLE
config in profiles.yaml isn't read

### ISSUE THREAD

**Issue by enkeboll** [analyst-collective/dbt#254]
In 0.6.0:

Config is retrieved at, for example, [here](https://github.com/analyst-collective/dbt/blob/4a00ff26fdf98cefdc2f34529310f52dbc15f4dc/dbt/main.py#L28) but the `profiles` object is scrubbed of the `config` key [here](https://github.com/analyst-collective/dbt/blob/4a00ff26fdf98cefdc2f34529310f52dbc15f4dc/dbt/project.py#L141)

**Comment by cmcarthur** [comment]
@enkeboll hey, thanks for writing in. we'll take a look.

**Comment by drewbanin** [comment]
fixed in 0.6.1 https://github.com/analyst-collective/dbt/blob/development/CHANGELOG.md#dbt-061
