### ISSUE TITLE
Connecting to redshift is a lie

### ISSUE THREAD

**Issue by henryhund** [analyst-collective/dbt#264]
I'm using Postgres, yet I still see "connecting to Redshift" when I do dbt run

https://github.com/analyst-collective/dbt/blob/2d0ea1bd6fff73bd2f17a916176022b15defbf97/dbt/runner.py#L630

**Comment by drewbanin** [comment]
good catch -- thanks @henryhund

**Comment by cmcarthur** [comment]
I'm already working on this in #259 cc @drewbanin

**Comment by cmcarthur** [comment]
will be fixed in #259
