### ISSUE TITLE
Need dependency resolution

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#3]
Running `dbt compile` and then `dbt run` causes an error in the current state of the models repo, because there are dependencies. Currently every time i `dbt compile` I need to go into `target` and rename folders, because currently they are just executed in alpha order. 

Ideally dependencies are simply inferred from the content of the SQL.

**Comment by drewbanin** [comment]
https://github.com/analyst-collective/dbt/pull/9

**Comment by drewbanin** [comment]
dagnabit
