### ISSUE TITLE
return connection information

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#30]
dbt's connection information should be able to be accessed by other code. this provides a convenient utility for credential management across all analytic code.

the current use case for this is using the redshift credentials within a jupyter notebook.

**Comment by jthandy** [comment]
this could solved via two potential routes: 
1. CLI function to return credentials or connect string
2. python function to return credentials or connect string

currently, the entire tool is based around the command line, but that would be awkward for the current use case. it certainly would be possible to execute it as a bash command from within the notebook, but that would be...strange. at the same time, it feels like `import dbt` within a notebook is a completely new thing that deserves some consideration. 

should all dbt functions be python-callable as well? if so, should that be designed as multiple APIs on top of the same core functionality (CLI integration, python integration)? are there design implications for this?

I'm not trying to open up a can of worms here--if we feel like the solution to this would be either hacky or cause more short-term problems than it solves, we don't have to do it right now.

**Comment by drewbanin** [comment]
@jthandy good idea, but i think we need to give this some more thought. Closing for now
