### ISSUE TITLE
dbt should run tests

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#4]
dbt should run tests and report on test success / failure.

**Comment by drewbanin** [comment]
@jthandy as of right now, the test "models" will be run, but they aren't actually reported back to the user. I think this is a good candidate for the next release

**Comment by jthandy** [comment]
@drewbanin yes totally agree. I think we should separate tests out from models in the future and have them act slightly differently. I intentionally didn't put this as a part of our launch milestone; it's not urgent.

**Comment by jthandy** [comment]
this is being addressed at this point but in other issues
