### ISSUE TITLE
dbt profiles should have environment schemas called out

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#44]
`dbt run` should take an environment argument:

`dbt run --dev`
`dbt run --prod`

This isn't a massive deal, but at the moment you have to go into profiles.yml and switch the schema. And that's vulnerable to forgetting that, in the future, you have in fact switched the schema and accidentally deploying to production when you didn't mean to.

**Comment by jthandy** [comment]
(I don't actually care about the specific commands. If you think `dbt run --env=prod` is better that's fine.

**Comment by drewbanin** [comment]
```bash
dbt debug --target dev # use "dev" target of default "user" profile
dbt debug --profile org-2 --profile "dev" # use "dev" target of "org-2" profile
dbt debug --profile org-2 --profile "prod" # use "prod" target of "org-2" profile
```
This works for `dbt (debug|compile|run|test)`

If this gets annoying, consider using a makefile:

```make
org1-dev:
  dbt compile --profile org-1 --profile dev
  dbt run --profile org-1 --profile dev

org1-prod:
  dbt compile --profile org-1 --profile prod
  dbt run --profile org-1 --profile prod
```

`dbt run` should invoke `dbt compile` in the future, so this is just a stopgap solution
