### ISSUE TITLE
test for referential integrity is awkward

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#45]
right now, dbt is assuming you're specifying referential integrity on the "one" side of the one-to-many relationship. this is awkward; you should ideally specify it on the "many" side of the relationship. what you're really doing in this case is checking "are there any values in this field that don't appear in the parent table?", so it's counterintuitive to specify it on the parent table, because it's actually validating the child table.

PLMK if this doesn't make sense. It should ideally just be a change to the construction of that one SQL statement. 

For now, I'm going to construct all of my schema.yml files to work with the way it is currently specified, but I'd prefer to migrate them over to the corrected format asap.

**Comment by drewbanin** [comment]
https://github.com/analyst-collective/dbt/pull/51

Going to merge this in the morning. This is a breaking change for existing schema files @jthandy
