### ISSUE TITLE
write unit tests

### ISSUE THREAD

**Issue by drewbanin** [analyst-collective/dbt#59]
PHASE 1:
- [x] test imports
- [ ] test compilation code
- [ ] test global args (`--profile`, `--target)
- [ ] test config file args (`profile`, `enabled/disabled`)

**Comment by jthandy** [comment]
@drewbanin are we implementing travis?

**Comment by drewbanin** [comment]
@jthandy yeah, we'll definitely use travis

**Comment by drewbanin** [comment]
*definitely*

using circle CI. Also, changing this issue from unit to integration tests. Higher ROI right now. Also closing
