### ISSUE TITLE
when rebuilding tables, dbt should use table renaming to minimize amount of time the table is unavailable

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#68]
rather than dropping the table and then rebuilding it from a query, it would be better to create a new table with a temporary name, wait for the query to finish, then drop the old table, then rename the new table to the correct name. this would result in a significantly smaller window in which the table was unavailable for querying.

**Comment by drewbanin** [comment]
hey @doncorrea-vroom - can you create a new issue if you're having an issue with dbt v0.16.1? Thanks!
