### ISSUE TITLE
allow users to specify the schema for a model

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#69]
right now, all models need to be deployed in a common schema. this is messy/confusing, but it allows the user to use schemas to manage test / production environments.

a more mature configuration would be to use separate databases or clusters for development and production, periodically copying data from production to test. this would free up all schemas within that database to be used, rather than needing to cordon them off into a single schema. this means that snowplow models could go into the snowplow schema, right along with the raw data. this is desirable.

we could easily infer schema names for a given model from the filename, as we currently do for table names: `{{schemaname}}.{{tablename}}.sql`, where `{{schemaname}}` could be optional and would therefore default back to the default schema name defined in profiles.yml.

**Comment by brynary** [comment]
Trying out dbt today and this was something I ran into right away. If this is an easy patch, I may be able to take a shot at implementing it (though my Python is rusty).

**Comment by jthandy** [comment]
Cool to see you trying it out! Can you share what kind of project you're using it for?

@drewbanin see above

**Comment by brynary** [comment]
Well, we're setting up our first ever data warehouse and BI infrastructure, so there are all sorts of models and analysis that we'll be developing and we're considering doing all of it on dbt. Right now what I'm playing with is using RJMetric PIpeline to get data into Redshift, dbt to transform the data, and then using another tool (e.g. Mode) to visualize and run reports... But this is my first usage of any/all of these tools so I don't really know what I'm doing yet.

Looks like you guys might be doing some consulting work in this space? Maybe we should connect via email.

**Comment by jthandy** [comment]
I would love to connect, absolutely. The stack you describe is what we're using with all of our consulting clients. Email me at firstname [at] fishtownanalytics.com.
