### ISSUE TITLE
self()

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#81]
implement a `self()` function that returns `schema_name.model_name`. this will be helpful in pre- and post-hooks as outlined here: https://github.com/analyst-collective/dbt/issues/22

**Comment by drewbanin** [comment]
@jthandy `self` is essentially a reserved word in object-oriented python, so trying to use `self` here clashes with the jinja2 [rendering implementation](https://github.com/pallets/jinja/blob/master/jinja2/environment.py#L967)

I'm thinking we go for `{{this}}` instead. not sure it needs to be a function

**Comment by jthandy** [comment]
Sure, sounds good to me!






On Mon, Aug 8, 2016 at 3:14 PM -0400, "Drew Banin" <notifications@github.com> wrote:












@jthandy self is essentially a reserved word in object-oriented python, so trying to use self here clashes with the jinja2 rendering implementation



I'm thinking we go for {{this}} instead. not sure it needs to be a function

**Comment by drewbanin** [comment]
https://github.com/analyst-collective/dbt/pull/94
